# Simple Docker Compose for New Tab - Essential Services Only
# For basic usage without nginx, redis, or monitoring

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: newtab-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DATABASE_FILE=/app/data/web_memory.db
      - QUERY_CACHE_FILE=/app/data/query_embeddings_cache.json
      - ARK_API_TOKEN=${ARK_API_TOKEN}
      - PYTHONPATH=/app
    volumes:
      - ./data/backend:/app/data
      - ./logs/backend:/app/logs
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
